<?php



/**
 * @link http://github.com/plus3network/PHPHelpers PHPHelpers Git Repository
 * @author Christopher Cowan
 * @copyright Copyright (c) 2010, Christopher Cowan, Plus 3 Network Inc. All rights reserved.
 * @license http://www.opensource.org/licenses/lgpl-2.1.php GNU Lesser General Public License
 **/

/**
 * This will set cookies in an Netscape Cookie file
 *
 * @return void
 * @author Christopher Cowan
 **/
if( !function_exists('set_cookies_in_file'))
{
	function set_cookies_in_file($cookies,$file)
	{
		$fh = fopen($file, 'w+');
		fwrite($fh, "# Netscape HTTP Cookie File\n# http://curl.haxx.se/rfc/cookie_spec.html\n# This file was generated by libcurl! Edit at your own risk.\n\n");
		foreach($cookies as $cookie) {
			if(isset($cookie['domain']) && isset($cookie['key']) && isset($cookie['value'])) {
				$line = array(
					'domain'	  => $cookie['domain'],
					'domain_only' => (isset($cookie['domain_only']) && $cookie['domain_only'])? 'TRUE' : 'FALSE',
					'path'		=> (isset($cookie['path']))? $cookie['path'] : '/',
					'secure'	  => (isset($cookie['secure']) && $cookie['secure'])? 'TRUE' : 'FALSE',
					'expires'	 => (isset($cookie['expires']))? $cookie['expires'] : 0,
					'key'		 => $cookie['key'],
					'value'	   => $cookie['value'],
				);
				fwrite($fh, "{$line['domain']}\t{$line['domain_only']}\t{$line['path']}\t{$line['secure']}\t{$line['expires']}\t{$line['key']}\t{$line['value']}\n");
			}
		}
		fclose($fh);
	}
}
/**
 * This will parse the cookies file
 *
 * @return void
 * @author Christopher Cowan
 **/
 
if( !function_exists('get_cookies_from_file'))
{
	function get_cookies_from_file($file)
	{
		if( !file_exists($file)) return [];
		
		$cookies = array();
		$fh = fopen($file, 'r');
		while(!feof($fh)) {
			$buffer = fgets($fh, 8192);
			if(preg_match('/^([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\n]+)$/', $buffer, $matches)) {
				$cookies[] = array(
					'domain'	  => $matches[1],
					'domain_only' => ($matches[2] == 'TRUE')? true : false,
					'path'		=> $matches[3],
					'secure'	  => ($matches[4] == 'TRUE')? true : false,
					'expires'	 => $matches[5],
					'key'		 => $matches[6],
					'value'	   => $matches[7],
				);
			}
		}
		fclose($fh);
		return $cookies;
	}
}